### ISSUE TITLE
Force push to master

### ISSUE THREAD

**Issue by tecywiz121** [levex/cgroups-rs#6]
Our `Cargo.lock` file pointed to commit 675d59d9428667a2e1efdb882c70cfe0277bc832 since those changes weren't released yet.

That commit seems to have disappeared from the repository, possibly as a result of a rebase and force push.

While it definitely isn't required, I'd really appreciate avoiding force pushes to master. It makes `git pull` less painful, and we can pin unreleased commits.

**Comment by levex** [comment]
Yeah, I force pushed. Sadly, somehow I messed up my local clone and that had some side-effects I couldn't fix otherwise. I'll add a protect to `master` now and everything will go through via PRs.

**Comment by levex** [comment]
Yeah, I pushed I apologize! Somehow I ended up messing up my branches locally enough (and maybe it was late at night as well) that warranted my use of forcing push. Honestly, in hindsight, I don't think anything warrants the use of force pushing. I have now protected the branch so GitHub will reject pushes directly.
